### ISSUE TITLE
Bug: blank lines at end of Markdown blocks are not collapsed

### ISSUE THREAD

**Issue by simonratner** [heyman/heynote#195]
**Describe the bug**
When markdown block ends with one or more blank lines, those lines remain in collapsed view.

**To Reproduce**
1. Create a markdown block ending in blank lines:
```
Markdown collapsed example
--------------------------

First line
Second line


```
![image](https://github.com/heyman/heynote/assets/667283/e94df437-c92d-4daa-a539-40437b698e74)

2. Collapse it:

![image](https://github.com/heyman/heynote/assets/667283/60a3d328-a9cb-4115-ba14-f61d93ef06c6)

**Expected behavior**
Trailing blank lines are not visible when collapsed.

**Desktop (please complete the following information):**
 - OS: Win11
 - Version 1.7.0

**Comment by heyman** [comment]
Should be fixed in the latest version.

**Comment by simonratner** [comment]
Still seeing this behaviour in 2.3.3. Interestingly the line count in collapsed block summary does not count the blank trailing lines (showing `3 lines` in this example), but they are still rendered.

I think i see what the issue is. When your markdown block starts with a heading, collapsing that heading sub-block conflicts with collapsing the whole block - there is no longer a way to collapse the whole block because clicking the gutter arrow only collapses the heading sub-block.

<img width="570" height="181" alt="Image" src="https://github.com/user-attachments/assets/7c7a8f16-5c32-47bd-bb8c-bf170a55cf5e" />

<img width="577" height="142" alt="Image" src="https://github.com/user-attachments/assets/ad74e2ba-af4d-46a7-b828-3e4e45d4e6ae" />

**Comment by simonratner** [comment]
Ctrl-P > Fold Block gives the desired result:

<img width="566" height="36" alt="Image" src="https://github.com/user-attachments/assets/ff3e6be2-678b-4ddb-baef-d963ed36ecf3" />

**Comment by heyman** [comment]
I can reproduce it, and i have an idea of what's going on. Will have to look into how to fix it.

As a work around, you should be able to fold the entire block using the keyboard shortcut `Ctrl-Alt-.` (or running the "Fold Block" command from the command palette).

**Comment by heyman** [comment]
*Now* it should be fixed in the latest beta version
